import {useEffect,useMemo,useRef,useState} from 'react';
import type {Attempt,Exercise,LiteralCard,Mode,StudySession} from './types';
import {getAll,put,saveStudyAnswers} from './storage';
import {isLiteralExerciseCurrent,matchingRound,normalizeAnswer,shuffled} from './study';

const methods:{id:Mode;icon:string;title:string;detail:string}[]=[
 {id:'test',icon:'A B',title:'Test',detail:'Cuatro opciones · Corrección automática'},
 {id:'flashcard',icon:'↔',title:'Flashcards',detail:'Recuerda, revela y valora'},
 {id:'cloze',icon:'___',title:'Completar',detail:'Palabras, números y plazos literales'},
 {id:'match',icon:'⇄',title:'Relacionar',detail:'Une pasajes con su artículo o anexo'},
 {id:'recall',icon:'✎',title:'Recuperación libre',detail:'Escribe tu recuerdo y compruébalo'}];
type Props={mode:Mode;setMode:(m:Mode)=>void;amount:number;setAmount:(n:number)=>void;available:Exercise[];bank:LiteralCard[];busy:boolean;selected:number[];articleCount:number;onPilot:(ids:number[])=>void;onReader:()=>void;onSave:()=>Promise<void>;onError:(s:string)=>void;requested?:Exercise[];clearRequest:()=>void};

export default function StudyDesk(props:Props){
 const {mode,setMode,amount,setAmount,available,bank,busy,onSave,onError}=props;
 const [session,setSession]=useState<StudySession>(),[saved,setSaved]=useState<StudySession[]>([]),[answer,setAnswer]=useState(''),[answers,setAnswers]=useState<Record<string,string>>({}),[revealed,setRevealed]=useState(false),[saving,setSaving]=useState(false),[onlyErrors,setOnlyErrors]=useState(false),[onlyDue,setOnlyDue]=useState(false),[previous,setPrevious]=useState<Attempt[]>([]),[dueIds,setDueIds]=useState<Set<string>>(new Set());
 const startLock=useRef(false),consumedRequest=useRef<Exercise[]|undefined>(undefined);
 const refresh=async()=>{const [s,a,m]=await Promise.all([getAll<StudySession>('sessions'),getAll<Attempt>('attempts'),getAll<{articleId:string;due:string}>('memory')]);setSaved(s.sort((a,b)=>b.updated.localeCompare(a.updated)));setPrevious(a);setDueIds(new Set(m.filter(m=>new Date(m.due)<=new Date()).map(m=>m.articleId)));};
 useEffect(()=>{refresh().catch(e=>onError(String(e)));},[]);
 const lastAttempts=useMemo(()=>{const map=new Map<string,Attempt>();for(const a of [...previous].sort((a,b)=>a.date.localeCompare(b.date)))map.set(a.exerciseId??a.articleId,a);return map;},[previous]);
 const filtered=available.filter(e=>(!onlyErrors||lastAttempts.get(e.literalId??e.article.id_articulo)?.success===false)&&(!onlyDue||dueIds.has(e.article.id_articulo)));
 const current=session?.questions[session.index];
 const batch=session?.mode==='match'?session.questions.slice(session.index,session.index+4):current?[current]:[];
 const recorded=batch.length>0&&batch.every(e=>session?.answers.some(a=>a.exerciseId===e.id));
 const invalid=session?.questions.some(e=>e.literalId&&!isLiteralExerciseCurrent(e,bank))??false;
 const matchChoices=useMemo(()=>shuffled(batch.map(e=>({id:e.matchKey??e.article.id_articulo,label:e.referenceLabel??`${e.article.id_norma.toUpperCase()} · ${e.article.rubrica}`}))),[session?.id,session?.index]);
 const reset=()=>{setAnswer('');setAnswers({});setRevealed(false);};
 async function start(items=filtered){if(!items.length||saving||startLock.current)return;startLock.current=true;setSaving(true);try{
  const chosen=items[0].mode==='match'?matchingRound(items,Math.min(amount,items.length)):shuffled(items).slice(0,amount).map(e=>({...e,options:e.options?shuffled(e.options):undefined}));
  if(!chosen.length)return;
  const now=new Date().toISOString(),newSession:StudySession={id:crypto.randomUUID(),created:now,updated:now,mode:chosen[0].mode,questions:chosen,index:0,answers:[],status:'active',questionCount:chosen.length};
  await put('sessions',newSession);setSession(newSession);reset();await refresh();
 }catch(e){onError('No se pudo iniciar la sesión: '+String(e));}finally{startLock.current=false;setSaving(false);}}
 useEffect(()=>{if(props.requested?.length&&props.requested!==consumedRequest.current){consumedRequest.current=props.requested;start(props.requested);props.clearRequest();}},[props.requested]);
 async function resume(s:StudySession){setSession(s);reset();props.onPilot([...new Set(s.questions.flatMap(e=>e.topicIds))]);setMode(s.mode);}
 async function finishAnswer(success?:boolean){if(!session||!current||saving||recorded||invalid)return;setSaving(true);try{
  const now=new Date().toISOString();
  const attempts=batch.map(e=>{const chosen=session.mode==='match'?answers[e.id]:answer|| (success?'Lo recordaba':'Necesito repasarlo');
   const correct=session.mode==='match'?(e.matchKey??e.article.id_articulo):e.answer;
   return {id:session.id+':'+e.id,date:now,articleId:e.article.id_articulo,topicIds:e.topicIds,mode:e.mode,question:e.prompt,chosen:session.mode==='match'?(matchChoices.find(c=>c.id===chosen)?.label??chosen):chosen,correct:session.mode==='match'?e.answer:correct,success:success??(normalizeAnswer(chosen)===normalizeAnswer(correct)),sourceHash:e.article.hash_texto,sourceUrl:e.article.url_fuente,exerciseId:e.literalId,sessionId:session.id,quote:e.quote,sourceCheck:e.sourceCheck} satisfies Attempt;
  });
  const updated={...session,updated:now,answers:[...session.answers,...attempts.map((a,i)=>({exerciseId:batch[i].id,chosen:a.chosen,success:a.success}))]};
  await saveStudyAnswers(attempts,updated);setSession(updated);setRevealed(true);await onSave();await refresh();
 }catch(e){onError('La respuesta no se ha guardado: '+String(e));}finally{setSaving(false);}}
 async function next(){if(!session||!recorded||saving)return;setSaving(true);try{const index=session.index+batch.length;const updated:StudySession={...session,index,updated:new Date().toISOString(),status:index>=session.questions.length?'completed':'active'};await put('sessions',updated);setSession(updated);reset();await refresh();}catch(e){onError(String(e));}finally{setSaving(false);}}
 const checks=bank.filter(c=>props.selected.includes(c.id_tema));
 const title=methods.find(m=>m.id===(session?.mode??mode))!;
 if(session?.status==='completed'){
  const good=session.answers.filter(a=>a.success).length,wrong=session.questions.filter(e=>session.answers.find(a=>a.exerciseId===e.id)?.success===false);
  return <section className="session-summary card"><span className="tag">SESIÓN GUARDADA</span><h2>Una sesión más, un paso adelante.</h2><p>{title.title} · {session.answers.length} ejercicios · {['flashcard','recall'].includes(session.mode)?'Recuerdo autoevaluado':'Corrección literal'}</p><div className="summary"><div><strong>{good}</strong><span>{['flashcard','recall'].includes(session.mode)?'Recordados':'Aciertos'}</span></div><div><strong>{session.answers.length-good}</strong><span>Para repasar</span></div><div><strong>{session.answers.length?Math.round(good*100/session.answers.length):0}%</strong><span>Esta sesión</span></div></div><div className="button-row"><button disabled={!wrong.length||saving} onClick={()=>start(wrong)}>Repasar los fallos ({wrong.length})</button><button className="secondary" onClick={()=>setSession(undefined)}>Preparar otra sesión</button></div><details><summary>Revisar todas las respuestas</summary>{session.questions.map(e=>{const a=session.answers.find(a=>a.exerciseId===e.id);return <div className="result-row" key={e.id}><strong>{a?.success?'✓':'↺'} {e.article.rubrica} · Tema {e.topicIds.join(', ')}</strong><p className="literal">{e.prompt}</p><p>Tu respuesta: {a?.chosen}</p><p>Respuesta literal: <strong>{e.answer}</strong></p><a href={e.article.url_fuente} target="_blank" rel="noreferrer">Fuente oficial ↗</a></div>;})}</details></section>;
 }
 if(session&&current){
  const completed=session.answers.length,total=session.questions.length,result=session.answers.find(a=>a.exerciseId===current.id);
  return <section className="exercise"><div className="exercise-top"><span className="tag">{title.title}</span><span>{session.index+1}{batch.length>1?'–'+(session.index+batch.length):''} / {total}</span><button className="text-button" onClick={()=>{setSession(undefined);reset();}}>Pausar · Guardado</button></div><progress className="session-progress" aria-label="Progreso de la sesión" value={completed} max={total}/><p className="small muted">{session.mode==='match'?'Relaciona cada pasaje con su referencia.':`Tema ${current.topicIds.join(', ')} · ${current.article.id_norma.toUpperCase()} · ${current.article.rubrica}`}</p>{invalid?<div className="alert error" role="alert">Una fuente de esta sesión ha cambiado o se ha retirado. Conservamos tu historial; prepara una sesión con el banco actual.</div>:<>
   {session.mode==='match'?<div className="matching-board">{batch.map((e,i)=>{const r=session.answers.find(a=>a.exerciseId===e.id);return <section className="match-item" key={e.id}><span className="topic-number">{i+1}</span><blockquote>{e.prompt.slice(0,240)}{e.prompt.length>240?'…':''}</blockquote><details><summary>Leer pasaje completo</summary><p className="literal">{e.prompt}</p></details><label>Referencia del pasaje {i+1}<select value={answers[e.id]??matchChoices.find(c=>c.label===r?.chosen)?.id??''} disabled={recorded||saving} onChange={event=>setAnswers(old=>({...old,[e.id]:event.target.value}))}><option value="">Elige un artículo o anexo</option>{matchChoices.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label>{r&&<div className={r.success?'answer-status success':'answer-status failure'}>{r.success?'✓ Relación correcta':'↺ Revisa la relación'}<p>{e.answer}</p><a href={e.article.url_fuente} target="_blank" rel="noreferrer">Fuente ↗</a></div>}</section>;})}</div>:<>
    <p className="eyebrow">{session.mode==='test'?'ELIGE LA EXPRESIÓN LITERAL':session.mode==='flashcard'?'RECUPERA LA EXPRESIÓN DE MEMORIA':session.mode==='recall'?'RECONSTRUYE EL PASAJE ANTES DE REVELARLO':'COMPLETA EL HUECO DEL TEXTO OFICIAL'}</p>
    <h2>{session.mode==='recall'?`«${(current.quote??current.prompt).split(/\s+/).slice(0,9).join(' ')}…»`:current.prompt}</h2>
    {session.mode==='test'?<div className="options">{current.options?.map((option,i)=>{const correct=recorded&&option===current.answer,wrong=recorded&&option===result?.chosen&&!result.success;return <button key={option} className={'secondary option '+(answer===option?'selected ':'')+(correct?'correct ':wrong?'incorrect ':'')} disabled={recorded||saving} onClick={()=>setAnswer(option)}><span>{String.fromCharCode(65+i)}</span>{option}{correct&&<b aria-label="Respuesta correcta">✓</b>}{wrong&&<b aria-label="Respuesta fallada">×</b>}</button>;})}</div>:session.mode==='cloze'?<form onSubmit={e=>{e.preventDefault();if(answer.trim())finishAnswer();}}><label>Completa el hueco<input autoComplete="off" value={recorded?(result?.chosen??answer):answer} disabled={recorded||saving} onChange={e=>setAnswer(e.target.value)} placeholder="Escribe la expresión literal"/></label></form>:session.mode==='recall'?<label>Mi recuerdo (opcional)<textarea value={recorded?(result?.chosen??answer):answer} disabled={recorded||saving} onChange={e=>setAnswer(e.target.value)} placeholder="Escribe lo que recuerdas. La comparación será con el pasaje oficial, sin calificación jurídica automática."/></label>:null}
   </>}
   {!recorded&&((session.mode==='flashcard'||session.mode==='recall')?!revealed?<button onClick={()=>setRevealed(true)}>Revelar respuesta</button>:null:<button disabled={saving||(session.mode==='match'?batch.some(e=>!answers[e.id]):!answer.trim())} onClick={()=>finishAnswer()}>Corregir y guardar</button>)}
   {(revealed||recorded)&&session.mode!=='match'&&<div className="solution" role="status">{recorded&&<h3>{result?.success?(session.mode==='flashcard'||session.mode==='recall'?'Lo recordabas':'Respuesta correcta'):'Para repasar'}</h3>}<span className="eyebrow">{session.mode==='recall'?'PASAJE OFICIAL':'RESPUESTA LITERAL'}</span><p className="answer-word">{session.mode==='recall'?'Comprueba tu recuerdo con el texto':current.answer}</p><blockquote className="literal official-quote">{current.quote??current.article.texto}</blockquote><p className="small">{current.explanation}</p><a href={current.article.url_fuente} target="_blank" rel="noreferrer">{current.article.rubrica} · Fuente oficial ↗</a>{current.sourceCheck&&<p className="small muted">Texto contrastado: {new Date(current.sourceCheck).toLocaleDateString('es-ES')}</p>}{!recorded&&<div className="button-row"><button disabled={saving} onClick={()=>finishAnswer(true)}>Lo recordaba</button><button className="secondary" disabled={saving} onClick={()=>finishAnswer(false)}>Necesito repasarlo</button></div>}</div>}
   {recorded&&<button disabled={saving} onClick={next}>{session.index+batch.length>=total?'Ver resultados':'Siguiente →'}</button>}
  </>}<p className="study-footnote">Pasajes contrastados con el BOE. El alcance y la vigencia jurídica global continúan pendientes de revisión.</p></section>;
 }
 return <><div className="pilot-banner"><div><span className="eyebrow">PRIMEROS PILOTOS CON TEXTO CONTRASTADO</span><h2>Empieza a practicar con fuentes a la vista.</h2><p>Derechos fundamentales, tráfico y seguridad vial penal. La comprobación es del texto literal; no presenta el tema completo como revisado jurídicamente.</p></div><div className="pilot-buttons">{[{id:2,name:'Derechos fundamentales'},{id:7,name:'Tráfico'},{id:26,name:'Seguridad vial penal'}].map(p=><button className="secondary" key={p.id} onClick={()=>props.onPilot([p.id])}>Tema {p.id} · {p.name}</button>)}<button className="text-button" onClick={()=>props.onPilot([2,7,26])}>Mezclar los tres pilotos →</button></div></div>
  <div className="method-grid" role="group" aria-label="Método de estudio">{methods.map(m=><button className={'method-card '+(mode===m.id?'selected':'')} key={m.id} aria-pressed={mode===m.id} onClick={()=>setMode(m.id)}><span className="method-icon" aria-hidden="true">{m.icon}</span><strong>{m.title}</strong><small>{m.detail}</small></button>)}</div>
  <div className="study-grid"><section className="card session-settings"><h2>Diseña tu sesión</h2><label>Número de ejercicios<input type="number" min={1} max={100} value={amount} onChange={e=>setAmount(Math.max(1,Math.min(100,Number(e.target.value)||1)))}/></label><label className="check"><input type="checkbox" checked={onlyErrors} onChange={e=>setOnlyErrors(e.target.checked)}/>Solo errores pendientes</label><label className="check"><input type="checkbox" checked={onlyDue} onChange={e=>setOnlyDue(e.target.checked)}/>Solo artículos con repaso pendiente</label><p><strong>{filtered.length}</strong> ejercicios disponibles{props.articleCount?` en ${props.articleCount} unidades elegidas`:' en tu selección de temas'}.</p>{mode==='match'&&<p className="small muted">Se usa un pasaje por artículo o concepto para evitar referencias duplicadas; las relaciones se presentan en grupos de hasta cuatro.</p>}<button disabled={busy||saving||!filtered.length||(mode==='match'&&new Set(filtered.map(e=>e.matchKey??e.article.id_articulo)).size<2)} onClick={()=>start()}>{busy?'Cargando legislación…':'Comenzar sesión'}</button>{amount>filtered.length&&filtered.length>0&&<p className="small muted">La sesión tendrá {filtered.length} ejercicios; no duplicamos ejercicios para completar el número solicitado.</p>}</section><section className="card"><h2>Tu selección, tus fuentes</h2><p>{checks.length?`${checks.length} pasajes literales contrastados en los temas seleccionados.`:'Elige uno de los tres pilotos para usar el banco disponible. Los demás temas siguen pendientes; no se rellenan con preguntas inventadas.'}</p><p>Las explicaciones muestran el pasaje oficial, su referencia y versión. Los fallos se guardan automáticamente. Flashcards y recuperación libre registran tu valoración del recuerdo.</p><button className="secondary" onClick={props.onReader}>Elegir artículos en el lector</button></section></div>
  {saved.some(s=>s.status==='active')&&<section className="card"><h2>Continuar una sesión</h2>{saved.filter(s=>s.status==='active').slice(0,4).map(s=><div className="review-row" key={s.id}><div><strong>{methods.find(m=>m.id===s.mode)?.title}</strong><p className="small muted">{s.answers.length} / {s.questions.length} respuestas · {new Date(s.updated).toLocaleString('es-ES')}</p></div><button className="secondary" onClick={()=>resume(s)}>Continuar sesión</button></div>)}</section>}
  {saved.some(s=>s.status==='completed')&&<section className="card"><h2>Últimas sesiones</h2>{saved.filter(s=>s.status==='completed').slice(0,5).map(s=><div className="review-row" key={s.id}><div><strong>{methods.find(m=>m.id===s.mode)?.title}</strong><p className="small muted">{s.answers.filter(a=>a.success).length} / {s.answers.length} · {new Date(s.updated).toLocaleDateString('es-ES')}</p></div><button className="text-button" onClick={()=>setSession(s)}>Ver resultados →</button></div>)}</section>}
 </>;
}
